### ISSUE TITLE
Compiler error when priority queue value is a complex type

### ISSUE THREAD

**Issue by intelligent-tester** [spider-gazelle/priority-queue#1]
This works
```
require "priority-queue"

queue = Priority::Queue(Array(String)).new
queue.push 10, ["S"]
```

> [gshah@workstation expt]$ crystal run src/expt.cr
> ["S"]

But this gives a compiler error

```
require "priority-queue"

queue = Priority::Queue(Tuple(Array(String))).new
queue.push 10, {["S"]}
```

> [gshah@workstation expt]$ crystal run src/expt.cr
> Showing last frame. Use --error-trace for full trace.
> 
> In /usr/lib/crystal/array.cr:1933:21
> 
>  1933 | @buffer.value = object
>                         ^-----
> Error: type must be Priority::Item(Tuple(Array(String))), not Priority::Item(Tuple(Array(String)))

Do we have any leads on how to fix this?

**Comment by intelligent-tester** [comment]
Also raised this on Crystal forum.
https://forum.crystal-lang.org/t/compiler-not-inferring-generic-type-with-meaningless-error/5070

**Comment by stakach** [comment]
I think we have to assume this is a compiler issue and not related to the shard...
Do let me know if you find otherwise :)
